name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  version:
      runs-on: []
      
    

      steps:
        - name: Set Version
          id: set-version
          run: eval echo "${{ secrets.AWS_ECR_PASSWORD }}"

 
